-- AlterTable
ALTER TABLE "Tamizaje" ADD COLUMN     "escalasCalculadas" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "glo_t" DROP NOT NULL,
ALTER COLUMN "emo_t" DROP NOT NULL,
ALTER COLUMN "con_t" DROP NOT NULL,
ALTER COLUMN "eje_t" DROP NOT NULL,
ALTER COLUMN "ctx_t" DROP NOT NULL,
ALTER COLUMN "rec_t" DROP NOT NULL,
ALTER COLUMN "reg_t" DROP NOT NULL,
ALTER COLUMN "bus_t" DROP NOT NULL;
